"""Closed-form IDM derivatives at equilibrium and the stability-constrained global calibration."""

import numpy as np
import pytest
import torch

from cf_stability.data.schema import DT, Event
from cf_stability.models.idm import IDM, IDM_PARAM_NAMES, idm_acc, idm_equilibrium_partials, idm_margin
from cf_stability.stability.analytic import criterion, partials
from cf_stability.stability.equilibrium import find_equilibria
from cf_stability.train.calibration import CalibrationConfig, calibrate_global, idm_stability_shortfall
from cf_stability.train.closed_loop import rollout_memoryless

CALIBRATED = {"v0": 29.57, "T": 0.676, "s0": 2.015, "a": 0.351, "b": 0.5}  # FollowNet HighD, fold 0
SPEEDS = tuple(float(v) for v in range(5, 31))


def theta(params: dict) -> torch.Tensor:
    return torch.tensor([params[k] for k in IDM_PARAM_NAMES], dtype=torch.float64)


def test_closed_form_equals_autograd():
    model = IDM(CALIBRATED).double().eval()
    eq = find_equilibria(model)
    assert eq.status[-1] == "none" and eq.found[:-1].all()  # 30 m/s is above v0
    v = eq.v[eq.found]
    s_e, f_s, f_dv, f_v = idm_equilibrium_partials(v, *theta(CALIBRATED))
    a_s, a_dv, a_v = partials(model, eq.s[eq.found], v)
    assert torch.allclose(s_e, eq.s[eq.found], rtol=0, atol=1e-9)
    for closed, auto in ((f_s, a_s), (f_dv, a_dv), (f_v, a_v)):
        assert torch.allclose(closed, auto, rtol=1e-9, atol=1e-12)
    margin = idm_margin(v, *theta(CALIBRATED))
    assert torch.allclose(margin, criterion(a_s, a_dv, a_v)["margin"], rtol=1e-9, atol=1e-12)
    # the calibrated IDM is string unstable at low speed and stable at high speed
    assert margin[0] < -0.1 and margin[v == 25.0] > 0.0
    assert torch.isnan(idm_margin(torch.tensor([30.0], dtype=torch.float64), *theta(CALIBRATED))).all()


def test_shortfall():
    t = theta(CALIBRATED)
    margin = torch.nan_to_num(idm_margin(torch.tensor(SPEEDS, dtype=torch.float64), *t), nan=-10.0)
    expected = torch.clamp(0.1 - margin, min=0.0).sum()
    assert idm_stability_shortfall(t, 0.1, SPEEDS) == pytest.approx(float(expected), rel=1e-12)
    population = torch.stack((t, t * 1.1))
    assert idm_stability_shortfall(population, 0.1, SPEEDS).shape == (2,)
    stable = theta({"v0": 35.0, "T": 1.0, "s0": 4.7, "a": 2.7, "b": 0.5})
    assert idm_stability_shortfall(stable, 0.4, SPEEDS) == 0.0


def events_of(params: dict, n_events: int = 4, n: int = 300) -> list[Event]:
    p = [params[k] for k in IDM_PARAM_NAMES]
    out = []
    for i in range(n_events):
        rng = np.random.default_rng(i)
        t = DT * np.arange(n)
        v_lead = 14.0 + 6.0 * np.sin(2 * np.pi * t / rng.uniform(15, 25) + rng.uniform(0, 6.0))
        x_lead = 40.0 + np.concatenate(([0.0], np.cumsum(0.5 * (v_lead[1:] + v_lead[:-1]) * DT)))
        res = rollout_memoryless(
            lambda s, dv, v: idm_acc(s, dv, v, *p), torch.tensor(x_lead), torch.tensor(v_lead),
            torch.tensor(20.0, dtype=torch.float64), torch.tensor(v_lead[0]),
        )  # fmt: skip
        s, v = res.s.numpy(), res.v.numpy()
        out.append(
            Event(
                event_id=f"syn/a/{i}|L{i}|0", dataset="syn", site="a", follower_id=f"syn/a/{i}", leader_id=f"syn/a/L{i}",
                t=t, s=s, dv=v - v_lead, v=v, a=res.a.numpy(), v_lead=v_lead, x_lead=x_lead, x_follower=x_lead - s,
            )  # fmt: skip
        )
    return out


def test_constrained_calibration_keeps_the_margin():
    events = events_of(CALIBRATED)
    free = calibrate_global(events, CalibrationConfig(maxiter=40, restarts=1, device="cpu"))
    assert "margin_min" not in free and free["objective"] < 0.02
    cfg = CalibrationConfig(maxiter=60, restarts=1, device="cpu", stability_margin=0.05)
    out = calibrate_global(events, cfg)
    assert out["stability_margin"] == 0.05 and out["margin_min"] >= 0.05 - 1e-3
    margins = idm_margin(torch.tensor(SPEEDS, dtype=torch.float64), *theta(out["params"]))
    assert torch.isfinite(margins).all() and out["params"]["v0"] > 30.0  # an equilibrium at every grid speed
    # the constraint costs accuracy on data generated by an unstable IDM, and the two objectives are consistent
    assert out["fit_objective"] > free["objective"]
    assert out["objective"] == pytest.approx(
        out["fit_objective"] + 10.0 * float(idm_stability_shortfall(theta(out["params"]), 0.05, SPEEDS)), rel=1e-9
    )
